#!/bin/bash


echo please insert web address to scrape.

read Web_Address

wget $Web_Address

cat index.html | grep "href=" | cut -f3 -d "/" | grep "\." | cut -f1 -d '"' | sort -u >> website.txt

index=(index.html.*)
for index in "${index[@]}"; do grep "href=" | cut -f3 -d "/" | grep "\." | cut -f1 -d '"' | sort -u >> website.txt; done


cat website.txt

for url in $(cat website.txt); do host $url; done | grep "has address" | cut -f4 -d "" | sort -u >> DomainIPs.txt
